### ISSUE TITLE
install not complete - don't finde files

### ISSUE THREAD

**Issue by pouryaeman** [cryptopool-builders/Multi-Pool-Installer#13]
**Describe the bug**
Please provide full information about the issue you are having. Submitting generic submissions such as "It crashed" with no other information will result in your request being closed.

**To Reproduce**
1. Which installer does this apply to: [e.g. YiiMP Single Install, YiiMP Multi Install, etc]
2. Did the issue happen while entering requested information or during the automated process:

**Screenshots**
Please add screenshots to help explain your problem.

**Server Information (please complete the following information):**
 - OS: [e.g. Ubuntu 16.04]
 - Host: [e.g. Digital Ocean]

**Additional information**
Add any other information about the problem here.

install erore not found file:
Downloading selected YiiMP Repo...

FAILED: sudo git clone https://github.com/cryptopool-builders/yiimp.git /home/crypto-data/yiimp/yiimp_setup/yiimp
-----------------------------------------
fatal: destination path '/home/crypto-data/yiimp/yiimp_setup/yiimp' already exists and is not an empty directory.

and please send eth-etc-btg-bch-dash github link to auto build coin and say which installer i should to install them

and i wan't know how coins automatic update details

and if you can write about auto config coins about

thanks for sipporting

**Comment by cryptopool-builders** [comment]
It tells you right here why it failed;

"fatal: destination path '/home/crypto-data/yiimp/yiimp_setup/yiimp' already exists and is not an empty directory."

the installer requires a fresh install so you have already tried to use the installer. Right now if the installer fails for whatever reason on the first go you must reinstall the server and start again. 

This could be changed in a future update when I get time to work on the code again.
