### ISSUE TITLE
Multi-Pool Yiimp install - Where's addport file?

### ISSUE THREAD

**Issue by gr33k** [cryptopool-builders/Multi-Pool-Installer#14]
Installed yiimp multi-server setup. For the most part it went pretty good (nice work man!).

The only thing I can't seem to find is addport. I don't remember if I used static ports (I do believe I did). However, it's nowhere to be found. I can't find it on the repo here either so... where the heck can I find addport (single and multi)? I checked all of my servers and can't find it on any.

Thank you for your work on this! Would Love to see it continue man :)

**Comment by gr33k** [comment]
single instance yiimp installed addport just fine. Here is the code for those that need it:

https://paste.thec0de.com/?ee8ead1e05a32e1d#+ayF2r28dEAH/QxNE4qUOIASkR4jBkps73Plx3PJHCE=

**Comment by cryptopool-builders** [comment]
see the wiki. https://github.com/cryptopool-builders/Multi-Pool-Installer/wiki
