### ISSUE TITLE
Installing MariaDB Repository fails

### ISSUE THREAD

**Issue by akshaynexus** [cryptopool-builders/Multi-Pool-Installer#15]
**Describe the bug**
 Installing MariaDB Repository...
An error occurred in line 65 of file system.sh:
  sudo add-apt-repository 'deb [arch=amd64,arm64,i386,ppc64el] http://mirror.one.com/mariadb/repo/10.4/ubuntu xenial main' >/dev/null 2>&1

**To Reproduce**
1. Run installer with yimp single setup
2. setup as usual,but use a vps with 19.10 ubuntu version

**Server Information (please complete the following information):**
 - OS: Ubuntu 19.10
 - Host: Vultr

**Comment by cryptopool-builders** [comment]
the installer is not setup to use Ubuntu 19.10. It only supports Ubuntu 16 and 18
