### ISSUE TITLE
Help adding Dash Core v0.14 to yiimp pool

### ISSUE THREAD

**Issue by CryptoGreekCafe** [cryptopool-builders/Multi-Pool-Installer#16]
Please help to merge the coinbase.cpp for Dash Core v0.14

Trying to add $AGM to single server yiimp pool.
Pool is currently rejecting blocks with message: ERROR Argoneum Block decode failed

Must support array for masternode payments instead of a single item in the Argoneum block template. Before Dash 0.13 it was a single object.  Since Dash 0.13 it is an array of object.

![image](https://user-images.githubusercontent.com/61160432/74677472-662e4f80-5186-11ea-93ac-889c5c0f1461.png)

**Comment by cryptopool-builders** [comment]
please check the latest code and let me know
