### ISSUE TITLE
bootstrap.sh is broken

### ISSUE THREAD

**Issue by cmaske00** [cryptopool-builders/Multi-Pool-Installer#2]
bash: line 41: cd: /root/multipool/install: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
bash: line 44: [: v1.0: unary operator expected
bash: /root/multipool/install/start.sh: No such file or directory

**Comment by cryptopool-builders** [comment]
code is not fully released yet. will be released within next few days
