### ISSUE TITLE
Yiimp Interface - Daemons tab with auto configuration display bug when coin name ends wit h a "d"

### ISSUE THREAD

**Issue by moppidoo** [cryptopool-builders/Multi-Pool-Installer#3]
**Describe the bug**
Installed Bitsend via daemonbuilder and the Autogenerated config seemed to have left out a "d", maybe due to confusion since coin name ended with a "d" and script thought it stands for daemon as in most coins

**To Reproduce**
Install a coin via daemonbuilder and name end with "d"

from the picture below, which can be seen that all references to **bitsend** (directory or file) became **bitsen**, actual directories/files generated by daemonbuilder script are correct, just the yiimp display bugged

**Screenshots**
Please add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/9251248/48167850-015a3780-e33d-11e8-8350-2c2a690fe728.png)

**Server Information (please complete the following information):**
 - OS: Ubuntu 16.04
 - Host: HostMyBytes

**Comment by cryptopool-builders** [comment]
Ive update the YiiMP code to resolve this. to fix it, modify the file:

`/home/crypto-data/yiimp/site/web/yaamp/modules/site/coin_form.php`

change both lines 290 and 380 to read:

`$program = substr($coin->program, 0, -1);`

Not that I have run in to many of them, but there will have to be another fix for coins that do not have 'd' at all on the coin name. Ill come up with a better solution for those coins.
