### ISSUE TITLE
stops building at letsencrypt

### ISSUE THREAD

**Issue by chronzz** [cryptopool-builders/Multi-Pool-Installer#4]
**Describe the bug**
installing nomp on fresh install. 
when it gets to letsencrypt it just sit there and nothing happens unless i press enter and the build continues. but the enter produces an error when the installer asks for eg Bitcoind and say "blank" in not a folder and crashes to home. dns and everything is set properly 

**To Reproduce**
NOMP
install on subdomain with ssl
stops doing anything at letsencrypt
press enter and will continue build

**Screenshots**
Please add screenshots to help explain your problem.

**Server Information (please complete the following information):**
 - OS: Ubuntu 16.04
 - Host: Digital Ocean

**Additional information**
Add any other information about the problem here.

**Comment by chronzz** [comment]
this issue only happens when using a subdomain.
i used a domain and install was fine

**Comment by cryptopool-builders** [comment]
now that most of the installer for yiimp is hopefully bug free, ill start working on this again
