### ISSUE TITLE
Feature Request - ***Adding new algo stratums***

### ISSUE THREAD

**Issue by moppidoo** [cryptopool-builders/Multi-Pool-Installer#5]
**Describe the bug**
Requires the ability to add stratums uncommon algo to the multipool installation

**Additional information**
Wanting to add Balloon (as experiment) but have no idea on how to approach, all I know is the stratum needed recompilation but did not want to break the code. In this case, source code (forked yiimp) provided by coin/chain developer already 
https://github.com/deftchain/yiimp

**Comment by cryptopool-builders** [comment]
ill look in to this soon
