### ISSUE TITLE
cannot open tty-output

### ISSUE THREAD

**Issue by edwinosky** [cryptopool-builders/Multi-Pool-Installer#6]
when executing the Multipool installer the installation is canceled automatically and says "can not open tty-output"

use ubuntu 16.04
if I execute the command tty I get this "yiimp @ vultr: ~$tty
"/dev/pts/3"

**Comment by cryptopool-builders** [comment]
not a bug, you are trying to su to the user, as the installer states after the user creation you must reboot or log out of the root account and log in as the user. 

Join our discord channel at https://discord.gg/UGbGvna, this is covered in the FAQ section

**Comment by herb1213** [comment]
cannot open tty-output
help me
