### ISSUE TITLE
Crashing or Ending after public IP question

### ISSUE THREAD

**Issue by Chapster85** [cryptopool-builders/Multi-Pool-Installer#7]
Hello,

The Yiimp single installer is dropping back to the prompt right after asking for the public IP. 
This is on a brand new Ubuntu 16.04 install (with updates applied and both git and curl installed).
No error message is shown.

Also, the NOMP installer quickly flashes two "no such file or directory" error messages and goes back right to the beginning.

**Comment by RoomanSr** [comment]
I'm having the exact same problem.

**Comment by cryptopool-builders** [comment]
ill check this later tonight for yiimp single. for NOMP i need to do a major code update
