### ISSUE TITLE
Internal Server Error on AdminPortal

### ISSUE THREAD

**Issue by cjbriere** [cryptopool-builders/Multi-Pool-Installer#8]
Fresh ubuntu install, no updates, ran the script and get this when I go to the /site/AdminPortal:

Internal Server Error
error_log(/home/crypto-data/yiimp/site/log/debug.log): failed to open stream: Permission denied
An internal error occurred while the Web server was processing your request. Please contact the webmaster to report this problem.

Thank you.

There is nothing prevalent when I look at the log.

**Comment by cjbriere** [comment]
It appears the first_boot.sh is not running on 1st boot.....

**Comment by cryptopool-builders** [comment]
usually if first_boot doesnt run there was some sort of error during the install usually with permissions. 

Ill try to add some debugging logs to it at another time.
