### ISSUE TITLE
Script is unable to build the stratum 

### ISSUE THREAD

**Issue by mario1987** [cryptopool-builders/Multi-Pool-Installer#9]
When I do a clean install  v.1.49 version the install will fail on the stratum. 

make -C algos
make[1]: Entering directory '/home/crypto-data/yiimp/yiimp_setup/yiimp/stratum/algos'
gcc -O2 -I.. -march=native -std=gnu99 -c cuckoo.c -o cuckoo.o
In file included from cuckoo.c:4:0:
cuckoo.h:8:18: fatal error: chrono: No such file or directory
compilation terminated.
makefile:39: recipe for target 'cuckoo.o' failed
make[1]: *** [cuckoo.o] Error 1
make[1]: Leaving directory '/home/crypto-data/yiimp/yiimp_setup/yiimp/stratum/algos'
Makefile:38: recipe for target 'projectcode1' failed
make: *** [projectcode1] Error 2

**Comment by cryptopool-builders** [comment]
fixed
